language: node_js
node_js:
  - 10

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - PLATFORM=linux
    - os: osx
      osx_image: xcode9.4
      env:
        - PLATFORM=mac

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
    - .electron-cache

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi

install:
  - npm config set progress=false
  - npm config set spin=false
  - npm install

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm run release:mac;
    else
      npm run release:linux;
    fi
  - TRAVIS_TAG=$(node -p -e "require('./package.json').version")

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  draft: true
  prerelease: true
  file_glob: true
  file:
    - release/**/*.dmg
    - release/**/*.AppImage
    - release/**/*.deb

after_deploy:
  - "echo 'Deploy successful, go get some sleep.'"

branches:
  only:
    - master